[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mlsnapshot"
version = "0.0.1"
authors = [
  { name="Riley Corzine", email="rileycorzine@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"